### ISSUE TITLE
Tests fail when a single worker executes multiple tests

### ISSUE THREAD

**Issue by jovial** [stackhpc/stackhpc-ipa-hardware-managers#3]
## steps to reproduce

clone the repo:
```
cd /tmp
git clone https://github.com/stackhpc/stackhpc-ipa-hardware-managers.git
cd stackhpc-ipa-hardware-managers
```
run tox to create the virtualenv (this may or may not fail depending on number of cpus):

```
tox
```
force tests to run serially so that a single worker will run more than one test:

```
source .tox/py27/bin/activate
ostestr --serial
```

## example output

```
{0} stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_evaluate_hardware_support [0.000143s] ... ok
{0} stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_bios_mismatch [0.003234s] ... ok
{0} stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_disabled [0.006458s] ... ok
{0} stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_missing_bios_version [0.031560s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/home/fluxoid/code/work/stackhpc-ipa-hardware-managers/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
        return func(*args, **keywargs)
      File "stackhpc_ipa_hardware_managers/tests/unit/test_system_bios.py", line 127, in test_verify_bios_version_missing_bios_version
        None)
      File "/usr/lib64/python2.7/unittest/case.py", line 993, in assertRaisesRegexp
        callable_obj(*args, **kwargs)
      File "/usr/lib64/python2.7/unittest/case.py", line 116, in __exit__
        "{0} not raised".format(exc_name))
    AssertionError: CleaningError not raised
    
{0} stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_missing_product_name [0.001321s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/home/fluxoid/code/work/stackhpc-ipa-hardware-managers/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
        return func(*args, **keywargs)
      File "stackhpc_ipa_hardware_managers/tests/unit/test_system_bios.py", line 116, in test_verify_bios_version_missing_product_name
        None)
      File "/usr/lib64/python2.7/unittest/case.py", line 993, in assertRaisesRegexp
        callable_obj(*args, **kwargs)
      File "/usr/lib64/python2.7/unittest/case.py", line 116, in __exit__
        "{0} not raised".format(exc_name))
    AssertionError: CleaningError not raised
    
{0} stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_missing_system_vendor [0.001438s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/home/fluxoid/code/work/stackhpc-ipa-hardware-managers/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
        return func(*args, **keywargs)
      File "stackhpc_ipa_hardware_managers/tests/unit/test_system_bios.py", line 105, in test_verify_bios_version_missing_system_vendor
        None)
      File "/usr/lib64/python2.7/unittest/case.py", line 993, in assertRaisesRegexp
        callable_obj(*args, **kwargs)
      File "/usr/lib64/python2.7/unittest/case.py", line 116, in __exit__
        "{0} not raised".format(exc_name))
    AssertionError: CleaningError not raised
    
{0} stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_ok [0.001101s] ... ok
{0} stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_ok_explicitly_enabled [0.001109s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "stackhpc_ipa_hardware_managers/tests/unit/test_system_bios.py", line 64, in test_verify_bios_version_ok_explicitly_enabled
        self._verify_bios_version_ok_explicitly_enabled(value)
      File "/home/fluxoid/code/work/stackhpc-ipa-hardware-managers/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
        return func(*args, **keywargs)
      File "stackhpc_ipa_hardware_managers/tests/unit/test_system_bios.py", line 71, in _verify_bios_version_ok_explicitly_enabled
        self.assertTrue(self.manager.verify_bios_version(self.node, None))
      File "stackhpc_ipa_hardware_managers/system_bios.py", line 117, in verify_bios_version
        expected_product_name = _get_expected_property(node, 'product_name')
      File "stackhpc_ipa_hardware_managers/system_bios.py", line 70, in _get_expected_property
        node_property))
    ironic_python_agent.errors.CleaningError: Clean step failed: Expected property 'system_vendor' not found. For cleaning to proceed you must set the property 'system_vendor/product_name' in the node's extra field, for example: $ openstack baremetal node set $NODE_ID --extra system_vendor/product_name=$VALUE
    
{0} stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_product_mismatch [0.001533s] ... FAILED

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/home/fluxoid/code/work/stackhpc-ipa-hardware-managers/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
        return func(*args, **keywargs)
      File "stackhpc_ipa_hardware_managers/tests/unit/test_system_bios.py", line 94, in test_verify_bios_version_product_mismatch
        None)
      File "/usr/lib64/python2.7/unittest/case.py", line 993, in assertRaisesRegexp
        callable_obj(*args, **kwargs)
      File "/usr/lib64/python2.7/unittest/case.py", line 127, in __exit__
        (expected_regexp.pattern, str(exc_value)))
    AssertionError: "^(?=.*\bPowerEdge R630\b)(?=.*\bT4000\b).*$" does not match "Clean step failed: Expected property 'system_vendor' not found. For cleaning to proceed you must set the property 'system_vendor/product_name' in the node's extra field, for example: $ openstack baremetal node set $NODE_ID --extra system_vendor/product_name=$VALUE"
    

==============================
Failed 5 tests - output below:
==============================

stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_missing_bios_version
------------------------------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/home/fluxoid/code/work/stackhpc-ipa-hardware-managers/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
        return func(*args, **keywargs)
      File "stackhpc_ipa_hardware_managers/tests/unit/test_system_bios.py", line 127, in test_verify_bios_version_missing_bios_version
        None)
      File "/usr/lib64/python2.7/unittest/case.py", line 993, in assertRaisesRegexp
        callable_obj(*args, **kwargs)
      File "/usr/lib64/python2.7/unittest/case.py", line 116, in __exit__
        "{0} not raised".format(exc_name))
    AssertionError: CleaningError not raised
    

stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_missing_product_name
------------------------------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/home/fluxoid/code/work/stackhpc-ipa-hardware-managers/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
        return func(*args, **keywargs)
      File "stackhpc_ipa_hardware_managers/tests/unit/test_system_bios.py", line 116, in test_verify_bios_version_missing_product_name
        None)
      File "/usr/lib64/python2.7/unittest/case.py", line 993, in assertRaisesRegexp
        callable_obj(*args, **kwargs)
      File "/usr/lib64/python2.7/unittest/case.py", line 116, in __exit__
        "{0} not raised".format(exc_name))
    AssertionError: CleaningError not raised
    

stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_missing_system_vendor
-------------------------------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/home/fluxoid/code/work/stackhpc-ipa-hardware-managers/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
        return func(*args, **keywargs)
      File "stackhpc_ipa_hardware_managers/tests/unit/test_system_bios.py", line 105, in test_verify_bios_version_missing_system_vendor
        None)
      File "/usr/lib64/python2.7/unittest/case.py", line 993, in assertRaisesRegexp
        callable_obj(*args, **kwargs)
      File "/usr/lib64/python2.7/unittest/case.py", line 116, in __exit__
        "{0} not raised".format(exc_name))
    AssertionError: CleaningError not raised
    

stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_ok_explicitly_enabled
-------------------------------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "stackhpc_ipa_hardware_managers/tests/unit/test_system_bios.py", line 64, in test_verify_bios_version_ok_explicitly_enabled
        self._verify_bios_version_ok_explicitly_enabled(value)
      File "/home/fluxoid/code/work/stackhpc-ipa-hardware-managers/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
        return func(*args, **keywargs)
      File "stackhpc_ipa_hardware_managers/tests/unit/test_system_bios.py", line 71, in _verify_bios_version_ok_explicitly_enabled
        self.assertTrue(self.manager.verify_bios_version(self.node, None))
      File "stackhpc_ipa_hardware_managers/system_bios.py", line 117, in verify_bios_version
        expected_product_name = _get_expected_property(node, 'product_name')
      File "stackhpc_ipa_hardware_managers/system_bios.py", line 70, in _get_expected_property
        node_property))
    ironic_python_agent.errors.CleaningError: Clean step failed: Expected property 'system_vendor' not found. For cleaning to proceed you must set the property 'system_vendor/product_name' in the node's extra field, for example: $ openstack baremetal node set $NODE_ID --extra system_vendor/product_name=$VALUE
    

stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_product_mismatch
--------------------------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "/home/fluxoid/code/work/stackhpc-ipa-hardware-managers/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
        return func(*args, **keywargs)
      File "stackhpc_ipa_hardware_managers/tests/unit/test_system_bios.py", line 94, in test_verify_bios_version_product_mismatch
        None)
      File "/usr/lib64/python2.7/unittest/case.py", line 993, in assertRaisesRegexp
        callable_obj(*args, **kwargs)
      File "/usr/lib64/python2.7/unittest/case.py", line 127, in __exit__
        (expected_regexp.pattern, str(exc_value)))
    AssertionError: "^(?=.*\bPowerEdge R630\b)(?=.*\bT4000\b).*$" does not match "Clean step failed: Expected property 'system_vendor' not found. For cleaning to proceed you must set the property 'system_vendor/product_name' in the node's extra field, for example: $ openstack baremetal node set $NODE_ID --extra system_vendor/product_name=$VALUE"
    


======
Totals
======
Ran: 9 tests in 0.0000 sec.
 - Passed: 4
 - Skipped: 0
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 5
Sum of execute time for each test: 0.0479 sec.

==============
Worker Balance
==============
 - Worker 0 (9 tests) => 0:00:00.053954

Slowest Tests:
Test id                                                                                                                          Runtime (s)
-------------------------------------------------------------------------------------------------------------------------------  -----------
stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_missing_bios_version   0.032
stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_disabled               0.006
stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_bios_mismatch          0.003
stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_product_mismatch       0.002
stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_missing_system_vendor  0.001
stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_missing_product_name   0.001
stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_ok_explicitly_enabled  0.001
stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_verify_bios_version_ok                     0.001
stackhpc_ipa_hardware_managers.tests.unit.test_system_bios.TestSystemBiosManager.test_evaluate_hardware_support                  0.000
```

**Comment by jovial** [comment]
fixed via #4
